"""s_a added unique constraint to subject ID

Revision ID: 0346cb7d3c5b
Revises: 36fcbc2d4014
Create Date: 2025-09-04 01:38:22.405711

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0346cb7d3c5b'
down_revision: Union[str, None] = '36fcbc2d4014'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'survey_answer', ['subject_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'survey_answer', type_='unique')
    # ### end Alembic commands ###
