"""fix survey answer fkey

Revision ID: 0412b21d0075
Revises: ca38dbda0f3e
Create Date: 2025-07-31 16:21:35.461999

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0412b21d0075'
down_revision: Union[str, None] = 'ca38dbda0f3e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    #op.drop_constraint(op.f('survey_answer_survey_config_id_key'), 'survey_answer', type_='unique')
    #op.drop_constraint(op.f('survey_answer_survey_question_id_key'), 'survey_answer', type_='unique')
    #op.drop_constraint(op.f('survey_answer_survey_question_id_fkey'), 'survey_answer', type_='foreignkey')

    #Recreate FK in survey answer
    op.create_foreign_key(
    "survey_answer_survey_question_id_fkey",
    "survey_answer",
    "survey_question",
    ["survey_config_id", "survey_question_id"],
    ["survey_config_id", "id"],
    ondelete="CASCADE",
    onupdate="CASCADE"
) # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('survey_answer_survey_question_id_fkey', 'survey_answer', type_='foreignkey')
    op.create_foreign_key(
        "survey_answer_survey_question_id_fkey",
        "survey_answer",
        "survey_question",
        ["survey_question_id"],
        ["id"],
        ondelete="CASCADE",
        onupdate="CASCADE"
    )
    op.create_unique_constraint(op.f('survey_answer_survey_question_id_key'), 'survey_answer', ['survey_question_id'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('survey_answer_survey_config_id_key'), 'survey_answer', ['survey_config_id'], postgresql_nulls_not_distinct=False)
    
    # ### end Alembic commands ###
