"""added reasearcher to study

Revision ID: 1120f57df71d
Revises: fde459c4a1d5
Create Date: 2025-08-04 16:33:14.732161

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1120f57df71d'
down_revision: Union[str, None] = 'fde459c4a1d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('study', sa.Column('researcher', sa.UUID(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('study', 'researcher')
    # ### end Alembic commands ###
