"""fixed survey mapping

Revision ID: 16a2f44abcf4
Revises: 61a66da78534
Create Date: 2025-07-14 11:17:26.269117

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '16a2f44abcf4'
down_revision: Union[str, None] = '61a66da78534'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'study', ['id'])
    op.create_unique_constraint(None, 'study_response', ['study_results_id'])
    op.create_unique_constraint(None, 'study_results', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'study_results', type_='unique')
    op.drop_constraint(None, 'study_response', type_='unique')
    op.drop_constraint(None, 'study', type_='unique')
    # ### end Alembic commands ###
