"""changed roles to list

Revision ID: 17a073c162a4
Revises: 1120f57df71d
Create Date: 2025-08-05 11:26:45.367881

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import ARRAY


# revision identifiers, used by Alembic.
revision: str = '17a073c162a4'
down_revision: Union[str, None] = '1120f57df71d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user","role")
    op.add_column('user', sa.Column('role', ARRAY(sa.Enum('RESEARCHER', 'STAFF', 'ADMIN', name='role', native_enum=False)), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user","role")
    op.add_column('user', sa.Column('role', sa.Enum('RESEARCHER', 'STAFF', 'ADMIN', name='role', native_enum=False), nullable=False))
    # ### end Alembic commands ###
