"""fix study debrief

Revision ID: 1ffe045f5740
Revises: aef8b0ed95f6
Create Date: 2025-07-22 16:38:27.688607

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1ffe045f5740'
down_revision: Union[str, None] = 'aef8b0ed95f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('files_config', 'study_debrief',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('files_config', 'study_debrief_bytes',
               existing_type=postgresql.BYTEA(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('files_config', 'study_debrief_bytes',
               existing_type=postgresql.BYTEA(),
               nullable=False)
    op.alter_column('files_config', 'study_debrief',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
