"""added o-m relationship with config and results

Revision ID: 221bf97bc8c0
Revises: 8a163fff4b72
Create Date: 2025-08-19 18:40:16.932252

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '221bf97bc8c0'
down_revision: Union[str, None] = '8a163fff4b72'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('study_results', sa.Column('config_id', sa.UUID(), nullable=False))
    op.create_index(op.f('ix_study_results_config_id'), 'study_results', ['config_id'], unique=False)
    op.create_foreign_key(None, 'study_results', 'study_config', ['config_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'study_results', type_='foreignkey')
    op.drop_index(op.f('ix_study_results_config_id'), table_name='study_results')
    op.drop_column('study_results', 'config_id')
    # ### end Alembic commands ###
