"""rename survey

Revision ID: 23c2233ea079
Revises: 489e36f2c4c5
Create Date: 2025-06-30 19:41:13.446464

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '23c2233ea079'
down_revision: Union[str, None] = '489e36f2c4c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('conclusion_config')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conclusion_config',
    sa.Column('study_config_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('show_results', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('survey', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['study_config_id'], ['study_config.id'], name=op.f('conclusion_config_study_config_id_fkey'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('study_config_id', name=op.f('conclusion_config_pkey')),
    sa.UniqueConstraint('study_config_id', name=op.f('conclusion_config_study_config_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    # ### end Alembic commands ###
