"""updated Survey, questions, answers

Revision ID: 261da6feaa89
Revises: f172eb6d9d8d
Create Date: 2025-06-10 16:45:16.676788

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '261da6feaa89'
down_revision: Union[str, None] = 'f172eb6d9d8d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('survey_answer', sa.Column('id', sa.Integer(), autoincrement=True, nullable=False))
    op.create_unique_constraint(None, 'survey_answer', ['survey_config_id'])
    op.drop_column('survey_config', 'answer')
    op.drop_column('survey_config', 'question')
    op.add_column('survey_question', sa.Column('id', sa.Integer(), autoincrement=True, nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('survey_question', 'id')
    op.add_column('survey_config', sa.Column('question', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('survey_config', sa.Column('answer', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'survey_answer', type_='unique')
    op.drop_column('survey_answer', 'id')
    # ### end Alembic commands ###
