"""Create Study Config Schema

Revision ID: 2b4669dbdf9f
Revises: 
Create Date: 2025-06-10 12:43:05.641072

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2b4669dbdf9f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('study_config',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('show_results', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('experiment_config',
    sa.Column('study_config_id', sa.UUID(), nullable=False),
    sa.Column('display_duration', sa.Integer(), nullable=False),
    sa.Column('pause_duration', sa.Integer(), nullable=False),
    sa.Column('display_method', sa.Enum('BINARY', 'GRADIENT', name='response_method', native_enum=False), nullable=False),
    sa.ForeignKeyConstraint(['study_config_id'], ['study_config.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('study_config_id'),
    sa.UniqueConstraint('study_config_id')
    )
    op.create_table('files_config',
    sa.Column('study_config_id', sa.UUID(), nullable=False),
    sa.Column('consent_form', sa.String(), nullable=False),
    sa.Column('image_list', sa.String(), nullable=False),
    sa.Column('instruction_set', sa.String(), nullable=False),
    sa.Column('debrief', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['study_config_id'], ['study_config.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('study_config_id'),
    sa.UniqueConstraint('study_config_id')
    )
    op.create_table('learn_config',
    sa.Column('study_config_id', sa.UUID(), nullable=False),
    sa.Column('display_duration', sa.Integer(), nullable=False),
    sa.Column('pause_duration', sa.Integer(), nullable=False),
    sa.Column('display_method', sa.Enum('SEQUENTIAL', 'RANDOM', name='display_method', native_enum=False), nullable=False),
    sa.ForeignKeyConstraint(['study_config_id'], ['study_config.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('study_config_id'),
    sa.UniqueConstraint('study_config_id')
    )
    op.create_table('survey_config',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('study_config_id', sa.UUID(), nullable=False),
    sa.Column('question', sa.String(), nullable=False),
    sa.Column('answer', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['study_config_id'], ['study_config.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('study_config_id')
    )
    op.create_table('wait_config',
    sa.Column('study_config_id', sa.UUID(), nullable=False),
    sa.Column('display_duration', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['study_config_id'], ['study_config.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('study_config_id'),
    sa.UniqueConstraint('study_config_id')
    )
    op.create_table('survey_answer',
    sa.Column('survey_config_id', sa.UUID(), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['survey_config_id'], ['survey_config.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('survey_config_id')
    )
    op.create_table('survey_question',
    sa.Column('survey_config_id', sa.UUID(), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['survey_config_id'], ['survey_config.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('survey_config_id'),
    sa.UniqueConstraint('survey_config_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('survey_question')
    op.drop_table('survey_answer')
    op.drop_table('wait_config')
    op.drop_table('survey_config')
    op.drop_table('learn_config')
    op.drop_table('files_config')
    op.drop_table('experiment_config')
    op.drop_table('study_config')
    # ### end Alembic commands ###
