"""updated file uploads for image list

Revision ID: 3682e746fdb4
Revises: aaee793fc450
Create Date: 2025-07-16 15:39:47.224985

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3682e746fdb4'
down_revision: Union[str, None] = 'aaee793fc450'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'study', ['id'])
    op.create_unique_constraint(None, 'study_response', ['study_results_id'])
    op.create_unique_constraint(None, 'study_results', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'study_results', type_='unique')
    op.drop_constraint(None, 'study_response', type_='unique')
    op.drop_constraint(None, 'study', type_='unique')
    # ### end Alembic commands ###
