"""updated survey answer

Revision ID: 36fcbc2d4014
Revises: 6781b45ea1c3
Create Date: 2025-09-04 01:24:02.520123

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '36fcbc2d4014'
down_revision: Union[str, None] = '6781b45ea1c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'conclusion_config', ['study_config_id'])
    op.create_unique_constraint(None, 'experiment_config', ['study_config_id'])
    op.create_unique_constraint(None, 'files_config', ['study_config_id'])
    op.create_unique_constraint(None, 'learn_config', ['study_config_id'])
    op.create_unique_constraint(None, 'study', ['id'])
    op.create_unique_constraint(None, 'study_config', ['id'])
    op.create_unique_constraint(None, 'study_results', ['id'])
    op.add_column('survey_answer', sa.Column('subject_id', sa.UUID(), nullable=False))
    op.alter_column('survey_answer', 'age',
               existing_type=sa.VARCHAR(),
               type_=sa.Integer(),
                postgresql_using="age::integer", 
               existing_nullable=False)
    op.drop_column('survey_answer', 'study_id')
    op.create_unique_constraint(None, 'survey_config', ['id'])
    op.create_unique_constraint(None, 'wait_config', ['study_config_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'wait_config', type_='unique')
    op.drop_constraint(None, 'survey_config', type_='unique')
    op.add_column('survey_answer', sa.Column('study_id', sa.UUID(), autoincrement=False, nullable=False))
    op.alter_column('survey_answer', 'age',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.drop_column('survey_answer', 'subject_id')
    op.drop_constraint(None, 'study_results', type_='unique')
    op.drop_constraint(None, 'study_config', type_='unique')
    op.drop_constraint(None, 'study', type_='unique')
    op.drop_constraint(None, 'learn_config', type_='unique')
    op.drop_constraint(None, 'files_config', type_='unique')
    op.drop_constraint(None, 'experiment_config', type_='unique')
    op.drop_constraint(None, 'conclusion_config', type_='unique')
    # ### end Alembic commands ###
