"""fixed survey question and answer keys

Revision ID: 489e36f2c4c5
Revises: 86457686a664
Create Date: 2025-06-30 18:19:11.003486

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '489e36f2c4c5'
down_revision: Union[str, None] = '86457686a664'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'conclusion_config', ['study_config_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'conclusion_config', type_='unique')
    # ### end Alembic commands ###
