"""readded survey

Revision ID: 4d1abec2a9fe
Revises: 6be81aa249f6
Create Date: 2025-06-30 20:26:11.085595

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4d1abec2a9fe'
down_revision: Union[str, None] = '6be81aa249f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('survey_config',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('study_config_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['study_config_id'], ['study_config.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('study_config_id')
    )
    op.create_unique_constraint(None, 'conclusion_config', ['study_config_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'conclusion_config', type_='unique')
    op.drop_table('survey_config')
    # ### end Alembic commands ###
