"""added reference to survey question from survey answer

Revision ID: 574ee7ac0317
Revises: edd1c97c3404
Create Date: 2025-07-09 14:53:58.443894

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '574ee7ac0317'
down_revision: Union[str, None] = 'edd1c97c3404'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('survey_answer', sa.Column('survey_question_id', sa.Integer(), nullable=False))
    op.create_unique_constraint(None, 'survey_answer', ['survey_question_id'])
    op.create_foreign_key(None, 'survey_answer', 'survey_question', ['survey_question_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'survey_answer', type_='foreignkey')
    op.drop_constraint(None, 'survey_answer', type_='unique')
    op.drop_column('survey_answer', 'survey_question_id')
    # ### end Alembic commands ###
