"""fix response typo

Revision ID: 61806310be71
Revises: df114362f7c2
Create Date: 2025-07-28 11:20:27.606761

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '61806310be71'
down_revision: Union[str, None] = 'df114362f7c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('study_response', sa.Column('response_time', sa.Float(), nullable=False))
    op.drop_column('study_response', 'reponse_time')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('study_response', sa.Column('reponse_time', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.drop_column('study_response', 'response_time')
    # ### end Alembic commands ###
