"""fixed timezone

Revision ID: 61a66da78534
Revises: 574ee7ac0317
Create Date: 2025-07-14 11:05:18.932475

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '61a66da78534'
down_revision: Union[str, None] = '574ee7ac0317'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('study',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('configuration_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['configuration_id'], ['study_config.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('configuration_id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('study_results',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('study_id', sa.UUID(), nullable=False),
    sa.Column('subject_id', sa.UUID(), nullable=False),
    sa.Column('submitted', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['study_id'], ['study.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('study_id'),
    sa.UniqueConstraint('subject_id')
    )
    op.create_table('study_response',
    sa.Column('study_results_id', sa.UUID(), nullable=False),
    sa.Column('image_id', sa.String(), nullable=False),
    sa.Column('reponse_time', sa.Float(), nullable=False),
    sa.Column('answer', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['study_results_id'], ['study_results.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('study_results_id'),
    sa.UniqueConstraint('study_results_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('study_response')
    op.drop_table('study_results')
    op.drop_table('study')
    # ### end Alembic commands ###
