"""restructured study and config relationship

Revision ID: 6781b45ea1c3
Revises: 221bf97bc8c0
Create Date: 2025-08-19 22:53:05.028647

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6781b45ea1c3'
down_revision: Union[str, None] = '221bf97bc8c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('study_configuration_id_key'), 'study', type_='unique')
    op.drop_constraint(op.f('study_configuration_id_fkey'), 'study', type_='foreignkey')
    op.drop_column('study', 'configuration_id')
    op.add_column('study_config', sa.Column('study_id', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'study_config', 'study', ['study_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'study_config', type_='foreignkey')
    op.drop_column('study_config', 'study_id')
    op.add_column('study', sa.Column('configuration_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('study_configuration_id_fkey'), 'study', 'study_config', ['configuration_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_unique_constraint(op.f('study_configuration_id_key'), 'study', ['configuration_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
