"""removd demographic survey

Revision ID: 6be81aa249f6
Revises: d3222d6fdc00
Create Date: 2025-06-30 20:21:14.506714

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6be81aa249f6'
down_revision: Union[str, None] = 'd3222d6fdc00'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conclusion_config',
    sa.Column('study_config_id', sa.UUID(), nullable=False),
    sa.Column('show_results', sa.Boolean(), nullable=False),
    sa.Column('survey', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['study_config_id'], ['study_config.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('study_config_id'),
    sa.UniqueConstraint('study_config_id')
    )
    op.drop_constraint('survey_question_survey_config_id_fkey', 'survey_question')
    op.drop_constraint('survey_answer_survey_config_id_fkey', 'survey_answer')
    op.drop_table('survey_question')
    op.drop_table('survey_config')
    op.drop_table('survey_answer')
    op.create_unique_constraint(None, 'experiment_config', ['study_config_id'])
    op.create_unique_constraint(None, 'files_config', ['study_config_id'])
    op.create_unique_constraint(None, 'learn_config', ['study_config_id'])
    op.create_unique_constraint(None, 'study_config', ['id'])
    op.create_unique_constraint(None, 'wait_config', ['study_config_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'wait_config', type_='unique')
    op.drop_constraint(None, 'study_config', type_='unique')
    op.drop_constraint(None, 'learn_config', type_='unique')
    op.drop_constraint(None, 'files_config', type_='unique')
    op.drop_constraint(None, 'experiment_config', type_='unique')
    op.create_table('survey_answer',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('survey_config_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('text', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['survey_config_id'], ['survey_config.id'], name=op.f('survey_answer_survey_config_id_fkey'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('survey_answer_pkey')),
    sa.UniqueConstraint('survey_config_id', name=op.f('survey_answer_survey_config_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('survey_config',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('study_config_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['study_config_id'], ['study_config.id'], name='survey_config_study_config_id_fkey', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='survey_config_pkey'),
    sa.UniqueConstraint('study_config_id', name='survey_config_study_config_id_key', postgresql_include=[], postgresql_nulls_not_distinct=False),
    postgresql_ignore_search_path=False
    )
    op.create_table('survey_question',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('survey_config_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('text', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['survey_config_id'], ['survey_config.id'], name=op.f('survey_question_survey_config_id_fkey'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('survey_question_pkey')),
    sa.UniqueConstraint('survey_config_id', name=op.f('survey_question_survey_config_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.drop_table('conclusion_config')
    # ### end Alembic commands ###
