"""rename survey table

Revision ID: 7342bf6620b9
Revises: a273ca69ddd8
Create Date: 2025-06-30 19:51:41.689171

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7342bf6620b9'
down_revision: Union[str, None] = 'a273ca69ddd8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('survey_question_survey_config_id_fkey'), 'survey_question', type_='foreignkey')
    op.drop_constraint(op.f('survey_answer_survey_config_id_fkey'), 'survey_answer', type_='foreignkey')
    op.drop_table('survey_config')

    op.create_table('config_survey',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('study_config_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['study_config_id'], ['study_config.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('study_config_id')
    )
    op.create_foreign_key(None, 'survey_answer', 'config_survey', ['survey_config_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key(None, 'survey_question', 'config_survey', ['survey_config_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'survey_question', type_='foreignkey')
    op.create_foreign_key(op.f('survey_question_survey_config_id_fkey'), 'survey_question', 'survey_config', ['survey_config_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_constraint(None, 'survey_answer', type_='foreignkey')
    op.create_foreign_key(op.f('survey_answer_survey_config_id_fkey'), 'survey_answer', 'survey_config', ['survey_config_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_table('survey_config',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('study_config_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['study_config_id'], ['study_config.id'], name=op.f('survey_config_study_config_id_fkey'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('survey_config_pkey')),
    sa.UniqueConstraint('id', name=op.f('survey_config_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False),
    sa.UniqueConstraint('study_config_id', name=op.f('survey_config_study_config_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.drop_table('config_survey')
    # ### end Alembic commands ###
