"""study config tail collision constraint

Revision ID: 781547d82d3f
Revises: d53ae390ed85
Create Date: 2025-09-29 22:07:45.168426

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '781547d82d3f'
down_revision: Union[str, None] = 'd53ae390ed85'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('uq_study_configuration_uuid_tail6', 'study_config', [sa.literal_column("right(replace(CAST(id AS TEXT), '-', ''), 6)")], unique=True, postgresql_using='btree')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_study_configuration_uuid_tail6', table_name='study_config', postgresql_using='btree')
    # ### end Alembic commands ###
