"""remove unique from study resopnse result id

Revision ID: 84b23a6c3d1e
Revises: 61806310be71
Create Date: 2025-07-29 11:08:07.812729

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '84b23a6c3d1e'
down_revision: Union[str, None] = '61806310be71'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('study_response_study_results_id_key'), 'study_response', type_='unique')
    #op.create_foreign_key('study_response_study_results_id_key','study_response','study_results',['study_results_id'],['id'],onupdate='CASCADE', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    #op.drop_constraint('study_response_study_results_id_key', 'study_response', type_='foreignkey')
    op.create_unique_constraint(op.f('study_response_study_results_id_key'), 'study_response', ['study_results_id'])
    #op.create_unique_constraint(op.f('study_response_study_results_id_key'), 'study_response', ['study_results_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
