"""added conclusion phase and file data type

Revision ID: 86457686a664
Revises: 95ccd59d7a7a
Create Date: 2025-06-30 15:47:00.956804

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '86457686a664'
down_revision: Union[str, None] = '95ccd59d7a7a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conclusion_config',
    sa.Column('study_config_id', sa.UUID(), nullable=False),
    sa.Column('show_results', sa.Boolean(), nullable=False),
    sa.Column('survey', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['study_config_id'], ['study_config.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('study_config_id'),
    sa.UniqueConstraint('study_config_id')
    )
    op.add_column('files_config', sa.Column('consent_form_bytes', postgresql.BYTEA(), nullable=False))
    op.add_column('files_config', sa.Column('study_instructions', sa.String(), nullable=False))
    op.add_column('files_config', sa.Column('study_instructions_bytes', postgresql.BYTEA(), nullable=False))
    op.add_column('files_config', sa.Column('study_debrief', sa.String(), nullable=False))
    op.add_column('files_config', sa.Column('study_debrief_bytes', postgresql.BYTEA(), nullable=False))
    op.drop_column('files_config', 'instruction_set')
    op.drop_column('files_config', 'debrief')
    op.drop_column('study_config', 'show_results')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('study_config', sa.Column('show_results', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('files_config', sa.Column('debrief', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('files_config', sa.Column('instruction_set', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('files_config', 'study_debrief_bytes')
    op.drop_column('files_config', 'study_debrief')
    op.drop_column('files_config', 'study_instructions_bytes')
    op.drop_column('files_config', 'study_instructions')
    op.drop_column('files_config', 'consent_form_bytes')
    op.drop_table('conclusion_config')
    # ### end Alembic commands ###
