"""fixed default for roles:


Revision ID: 8a163fff4b72
Revises: 17a073c162a4
Create Date: 2025-08-05 11:53:47.381169

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import ARRAY

# revision identifiers, used by Alembic.
revision: str = '8a163fff4b72'
down_revision: Union[str, None] = '17a073c162a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user","role")
    role_enum=sa.Enum('RESEARCHER', 'STAFF', 'ADMIN', name='role', native_enum=False)
    role_enum.create(op.get_bind())
    op.add_column('user', sa.Column('role', ARRAY(role_enum), nullable=False,
                                    server_default=sa.text("ARRAY['RESEARCHER']")))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user","role")
    op.add_column('user', sa.Column('role', ARRAY(sa.Enum('RESEARCHER', 'STAFF', 'ADMIN', name='role', native_enum=False)), nullable=False))
    # ### end Alembic commands ###
