"""add upload files table

Revision ID: 8d046ab72aef
Revises: cbf70ef83868
Create Date: 2025-07-01 10:35:11.647333

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8d046ab72aef'
down_revision: Union[str, None] = 'cbf70ef83868'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('files_config',
    sa.Column('study_config_id', sa.UUID(), nullable=False),
    sa.Column('consent_form', sa.String(), nullable=False),
    sa.Column('consent_form_bytes', postgresql.BYTEA(), nullable=False),
    sa.Column('learning_image_list', sa.String(), nullable=False),
    sa.Column('experiment_image_list', sa.String(), nullable=False),
    sa.Column('study_instructions', sa.String(), nullable=False),
    sa.Column('study_instructions_bytes', postgresql.BYTEA(), nullable=False),
    sa.Column('study_debrief', sa.String(), nullable=False),
    sa.Column('study_debrief_bytes', postgresql.BYTEA(), nullable=False),
    sa.ForeignKeyConstraint(['study_config_id'], ['study_config.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('study_config_id'),
    sa.UniqueConstraint('study_config_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('files_config')
    # ### end Alembic commands ###
