"""readded questions and answers

Revision ID: 8f32f2bf1a6d
Revises: 073bb58a07ba
Create Date: 2025-07-01 10:30:31.493342

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8f32f2bf1a6d'
down_revision: Union[str, None] = '073bb58a07ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('files_config')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('files_config',
    sa.Column('study_config_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('consent_form', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('consent_form_bytes', postgresql.BYTEA(), autoincrement=False, nullable=False),
    sa.Column('learning_image_list', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('experiment_image_list', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('study_instructions', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('study_instructions_bytes', postgresql.BYTEA(), autoincrement=False, nullable=False),
    sa.Column('study_debrief', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('study_debrief_bytes', postgresql.BYTEA(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['study_config_id'], ['study_config.id'], name=op.f('files_config_study_config_id_fkey'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('study_config_id', name=op.f('files_config_pkey')),
    sa.UniqueConstraint('study_config_id', name=op.f('files_config_study_config_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    # ### end Alembic commands ###
