"""Update survey_answer table schema

Revision ID: 8feaa7d41925
Revises: 97e53cd7f4dd
Create Date: 2025-08-17 23:10:55.446560

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8feaa7d41925'
down_revision: Union[str, None] = '97e53cd7f4dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('survey_question')
    op.add_column('survey_answer', sa.Column('study_id', sa.UUID(), nullable=False))
    op.drop_constraint(op.f('survey_answer_survey_config_id_fkey'), 'survey_answer', type_='foreignkey')
    op.drop_column('survey_answer', 'survey_config_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('survey_answer', sa.Column('survey_config_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('survey_answer_survey_config_id_fkey'), 'survey_answer', 'survey_config', ['survey_config_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_column('survey_answer', 'study_id')
    op.create_table('survey_question',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('survey_config_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('text', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['survey_config_id'], ['survey_config.id'], name=op.f('survey_question_survey_config_id_fkey'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('survey_config_id', 'id', name=op.f('survey_question_pkey'))
    )
    # ### end Alembic commands ###
