"""make debrief nullable

Revision ID: 95ccd59d7a7a
Revises: 5e4d2aa5169a
Create Date: 2025-06-24 18:51:57.797648

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '95ccd59d7a7a'
down_revision: Union[str, None] = '5e4d2aa5169a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('files_config', 'debrief',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('files_config', 'debrief',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
