"""Pivoted survey_answer table with age, sex, race columns

Revision ID: 97e53cd7f4dd
Revises: 9e1d55a06dc7
Create Date: 2025-08-17 22:26:50.240856

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '97e53cd7f4dd'
down_revision: Union[str, None] = '9e1d55a06dc7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('survey_answer', sa.Column('age', sa.String(), nullable=False))
    op.add_column('survey_answer', sa.Column('sex', sa.String(), nullable=False))
    op.add_column('survey_answer', sa.Column('race', sa.String(), nullable=False))
    op.drop_constraint(op.f('survey_answer_survey_config_id_key'), 'survey_answer', type_='unique')
    op.drop_constraint(op.f('survey_answer_survey_question_id_key'), 'survey_answer', type_='unique')
    op.drop_constraint(op.f('survey_answer_survey_question_id_fkey'), 'survey_answer', type_='foreignkey')
    op.drop_column('survey_answer', 'text')
    op.drop_column('survey_answer', 'survey_question_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('survey_answer', sa.Column('survey_question_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('survey_answer', sa.Column('text', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('survey_answer_survey_question_id_fkey'), 'survey_answer', 'survey_question', ['survey_config_id', 'survey_question_id'], ['survey_config_id', 'id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_unique_constraint(op.f('survey_answer_survey_question_id_key'), 'survey_answer', ['survey_question_id'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('survey_answer_survey_config_id_key'), 'survey_answer', ['survey_config_id'], postgresql_nulls_not_distinct=False)
    op.drop_column('survey_answer', 'race')
    op.drop_column('survey_answer', 'sex')
    op.drop_column('survey_answer', 'age')
    # ### end Alembic commands ###
