"""added id to study response

Revision ID: 9e1d55a06dc7
Revises: 8a4f8827b533
Create Date: 2025-07-29 11:47:03.899303

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e1d55a06dc7'
down_revision: Union[str, None] = '8a4f8827b533'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('study_response', sa.Column('id', sa.Integer(), nullable=False))
    op.drop_constraint('study_response_pkey','study_response')
    op.create_primary_key('study_response_pkey','study_response',['study_results_id','id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('study_response_pkey','study_response')
    op.drop_column('study_response', 'id')
    op.create_primary_key('study_response_pkey','study_response',['study_results_id'])
    # ### end Alembic commands ###
