"""removed nullable on study debrief bytes

Revision ID: aef8b0ed95f6
Revises: f7997377261d
Create Date: 2025-07-22 16:27:09.313097

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aef8b0ed95f6'
down_revision: Union[str, None] = 'f7997377261d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "files_config",
        "study_debrief_bytes",
        existing_type=sa.LargeBinary(),
        nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "files_config",
        "study_debrief_bytes",
        existing_type=sa.LargeBinary(),
        nullable=False
    )
    # ### end Alembic commands ###
