"""changed conclusion survey nullable

Revision ID: af14eb1653f8
Revises: 15d76b366a4c
Create Date: 2025-07-10 12:32:27.431791

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'af14eb1653f8'
down_revision: Union[str, None] = '15d76b366a4c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('conclusion_config', 'survey',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.create_unique_constraint(None, 'conclusion_config', ['study_config_id'])
    op.create_unique_constraint(None, 'experiment_config', ['study_config_id'])
    op.create_unique_constraint(None, 'files_config', ['study_config_id'])
    op.create_unique_constraint(None, 'learn_config', ['study_config_id'])
    op.create_unique_constraint(None, 'study_config', ['id'])
    op.create_unique_constraint(None, 'survey_config', ['id'])
    op.create_unique_constraint(None, 'wait_config', ['study_config_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'wait_config', type_='unique')
    op.drop_constraint(None, 'survey_config', type_='unique')
    op.drop_constraint(None, 'study_config', type_='unique')
    op.drop_constraint(None, 'learn_config', type_='unique')
    op.drop_constraint(None, 'files_config', type_='unique')
    op.drop_constraint(None, 'experiment_config', type_='unique')
    op.drop_constraint(None, 'conclusion_config', type_='unique')
    op.alter_column('conclusion_config', 'survey',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###
