"""fix survey answer foreign key

Revision ID: c67aeda0767d
Revises: 0412b21d0075
Create Date: 2025-07-31 16:37:36.355485

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import true

# revision identifiers, used by Alembic.
revision: str = 'c67aeda0767d'
down_revision: Union[str, None] = 'ca38dbda0f3e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('survey_answer_survey_config_id_fkey'), 'survey_answer', type_='foreignkey', if_exists=true)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(op.f('survey_answer_survey_config_id_fkey'), 'survey_answer', 'survey_config', ['survey_config_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    # ### end Alembic commands ###
