"""readd survey question and answer tables

Revision ID: cbf70ef83868
Revises: b9c0211d2d9e
Create Date: 2025-07-01 10:34:01.566225

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cbf70ef83868'
down_revision: Union[str, None] = 'b9c0211d2d9e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('survey_answer',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('survey_config_id', sa.UUID(), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['survey_config_id'], ['survey_config.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('survey_config_id')
    )
    op.create_table('survey_question',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('survey_config_id', sa.UUID(), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['survey_config_id'], ['survey_config.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('survey_config_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('survey_question')
    op.drop_table('survey_answer')
    # ### end Alembic commands ###
