"""conclusion phase survey

Revision ID: cfde1e95dec6
Revises: af14eb1653f8
Create Date: 2025-07-14 14:50:56.640989

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cfde1e95dec6'
down_revision: Union[str, None] = 'af14eb1653f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conclusion_config', sa.Column('has_survey', sa.Boolean(), nullable=True))
    op.drop_column('conclusion_config', 'survey')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conclusion_config', sa.Column('survey', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('conclusion_config', 'has_survey')
    # ### end Alembic commands ###
