"""added composite pk to survey questions

Revision ID: df114362f7c2
Revises: 1ffe045f5740
Create Date: 2025-07-23 12:35:44.033698

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'df114362f7c2'
down_revision: Union[str, None] = '1ffe045f5740'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    #Drop Dependant FK in survey answer
    op.drop_constraint("survey_answer_survey_question_id_fkey", "survey_answer", type_="foreignkey")
    #Drop Survey Question PK
    op.drop_constraint("survey_question_pkey", "survey_question", type_="primary")
    #Drop Survey Answer PK
    op.drop_constraint("survey_answer_pkey", "survey_answer", type_="primary")
    #Create composite PK in Survey Question
    op.create_primary_key(
        "survey_question_pkey",
        "survey_question",
        ["survey_config_id", "id"]
    )
    #Create composite PK in Survey Answer
    op.create_primary_key(
        "survey_answer_pkey",
        "survey_answer",
        ["survey_config_id","survey_question_id", "id"]
    )
    #Recreate FK in survey answer
    op.create_foreign_key(
    "survey_answer_survey_question_id_fkey",
    "survey_answer",
    "survey_question",
    ["survey_config_id", "survey_question_id"],
    ["survey_config_id", "id"],
    ondelete="CASCADE",
    onupdate="CASCADE"
)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("survey_answer_survey_question_id_fkey", "survey_answer", type_="foreignkey")
    op.drop_constraint("survey_answer_pkey", "survey_answer", type_="primary")
    op.drop_constraint("survey_question_pkey", "survey_question", type_="primary")

    op.create_primary_key(
        "survey_question_pkey",
        "survey_question",
        ["id"]
    )

    op.create_primary_key(
        "survey_answer_pkey",
        "survey_answer",
        ["id"]
    )

    op.create_foreign_key(
        "survey_answer_survey_question_id_fkey",
        "survey_answer",
        "survey_question",
        ["survey_question_id"],
        ["id"],
        ondelete="CASCADE",
        onupdate="CASCADE"
    )
    # ### end Alembic commands ###
