"""fixed back populate on survey

Revision ID: eb3d6a4c9d73
Revises: 90f6e05b7bcd
Create Date: 2025-06-30 20:31:42.746495

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb3d6a4c9d73'
down_revision: Union[str, None] = '90f6e05b7bcd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'survey_config', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'survey_config', type_='unique')
    # ### end Alembic commands ###
