"""update bidirectional refrences

Revision ID: f172eb6d9d8d
Revises: 2b4669dbdf9f
Create Date: 2025-06-10 16:26:23.742503

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f172eb6d9d8d'
down_revision: Union[str, None] = '2b4669dbdf9f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'experiment_config', ['study_config_id'])
    op.create_unique_constraint(None, 'files_config', ['study_config_id'])
    op.create_unique_constraint(None, 'learn_config', ['study_config_id'])
    op.create_unique_constraint(None, 'study_config', ['id'])
    op.create_unique_constraint(None, 'survey_config', ['id'])
    op.create_unique_constraint(None, 'survey_question', ['survey_config_id'])
    op.create_unique_constraint(None, 'wait_config', ['study_config_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'wait_config', type_='unique')
    op.drop_constraint(None, 'survey_question', type_='unique')
    op.drop_constraint(None, 'survey_config', type_='unique')
    op.drop_constraint(None, 'study_config', type_='unique')
    op.drop_constraint(None, 'learn_config', type_='unique')
    op.drop_constraint(None, 'files_config', type_='unique')
    op.drop_constraint(None, 'experiment_config', type_='unique')
    # ### end Alembic commands ###
