"""removed non nullable from study debrief upload

Revision ID: f7997377261d
Revises: b4020eb92e2b
Create Date: 2025-07-22 16:23:47.031073

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f7997377261d'
down_revision: Union[str, None] = 'b4020eb92e2b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "files_config",
        "study_debrief",
        existing_type=sa.String(),
        nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "files_config",
        "study_debrief",
        existing_type=sa.String(),
        nullable=False
    )
    # ### end Alembic commands ###
